-- HLS FRP content management schema for Supabase.
-- Run this file first in Supabase SQL Editor, then run seed.sql.

create extension if not exists pgcrypto;

create table if not exists public.hls_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.hls_product_categories (
  id text primary key check (id ~ '^[a-z0-9][a-z0-9-]{1,79}$'),
  name jsonb not null default '{}'::jsonb,
  description jsonb not null default '{}'::jsonb,
  image text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hls_products (
  id text primary key check (id ~ '^[a-z0-9][a-z0-9-]{1,79}$'),
  category_id text not null references public.hls_product_categories(id) on update cascade,
  name jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  features jsonb not null default '[]'::jsonb check (jsonb_typeof(features) = 'array'),
  applications jsonb not null default '{}'::jsonb,
  specifications jsonb not null default '{}'::jsonb,
  images text[] not null default '{}',
  spec_images text[] not null default '{}',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hls_news (
  id bigint generated by default as identity primary key,
  title jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  body jsonb not null default '[]'::jsonb check (jsonb_typeof(body) = 'array'),
  source jsonb not null default '{}'::jsonb,
  author text not null default '',
  views integer not null default 0 check (views >= 0),
  published_at date not null default current_date,
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hls_locations (
  id text primary key check (id ~ '^[a-z0-9][a-z0-9-]{1,79}$'),
  region jsonb not null default '{}'::jsonb,
  company jsonb not null default '{}'::jsonb,
  address jsonb not null default '{}'::jsonb,
  image text not null default '',
  phone text not null default '',
  fax text not null default '',
  email text not null default '',
  website text not null default '',
  line text not null default '',
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hls_inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254),
  phone text,
  message text not null check (char_length(message) between 1 and 2000),
  language text not null default 'zh' check (language in ('zh', 'zh-CN', 'en', 'th')),
  source_page text,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed', 'spam')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hls_media (
  id uuid primary key default gen_random_uuid(),
  bucket_id text not null default 'hls-site-assets' check (bucket_id = 'hls-site-assets'),
  storage_path text not null unique,
  public_url text not null unique,
  original_name text not null check (char_length(original_name) between 1 and 500),
  original_size_bytes bigint,
  mime_type text not null default 'image/webp' check (mime_type = 'image/webp'),
  width integer not null check (width between 1 and 30000),
  height integer not null check (height between 1 and 30000),
  size_bytes bigint not null check (size_bytes between 1 and 10485760),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.hls_media add column if not exists original_size_bytes bigint;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'hls_media_original_size_check'
      and conrelid = 'public.hls_media'::regclass
  ) then
    alter table public.hls_media add constraint hls_media_original_size_check
      check (original_size_bytes is null or original_size_bytes between 1 and 26214400);
  end if;
end;
$$;

create index if not exists hls_products_category_order_idx on public.hls_products(category_id, sort_order);
create index if not exists hls_news_published_date_idx on public.hls_news(published, published_at desc);
create index if not exists hls_locations_published_order_idx on public.hls_locations(published, sort_order);
create index if not exists hls_inquiries_status_created_idx on public.hls_inquiries(status, created_at desc);
create index if not exists hls_media_created_at_idx on public.hls_media(created_at desc);
create unique index if not exists hls_media_original_signature_idx
on public.hls_media (lower(original_name), original_size_bytes)
where original_size_bytes is not null;

create or replace function public.hls_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists hls_product_categories_updated_at on public.hls_product_categories;
create trigger hls_product_categories_updated_at before update on public.hls_product_categories
for each row execute function public.hls_set_updated_at();
drop trigger if exists hls_products_updated_at on public.hls_products;
create trigger hls_products_updated_at before update on public.hls_products
for each row execute function public.hls_set_updated_at();
drop trigger if exists hls_news_updated_at on public.hls_news;
create trigger hls_news_updated_at before update on public.hls_news
for each row execute function public.hls_set_updated_at();
drop trigger if exists hls_locations_updated_at on public.hls_locations;
create trigger hls_locations_updated_at before update on public.hls_locations
for each row execute function public.hls_set_updated_at();
drop trigger if exists hls_inquiries_updated_at on public.hls_inquiries;
create trigger hls_inquiries_updated_at before update on public.hls_inquiries
for each row execute function public.hls_set_updated_at();

create or replace function public.hls_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.hls_admins where user_id = auth.uid()
  );
$$;

create or replace function public.hls_get_site_content()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'categories', coalesce((
      select jsonb_agg(to_jsonb(item) - 'created_at' - 'updated_at' - 'published' order by item.sort_order, item.id)
      from public.hls_product_categories item where item.published
    ), '[]'::jsonb),
    'products', coalesce((
      select jsonb_agg(to_jsonb(item) - 'created_at' - 'updated_at' - 'published' order by item.sort_order, item.id)
      from public.hls_products item where item.published
    ), '[]'::jsonb),
    'news', coalesce((
      select jsonb_agg(to_jsonb(item) - 'created_at' - 'updated_at' - 'published' order by item.published_at desc, item.id desc)
      from public.hls_news item where item.published
    ), '[]'::jsonb),
    'locations', coalesce((
      select jsonb_agg(to_jsonb(item) - 'created_at' - 'updated_at' - 'published' order by item.sort_order, item.id)
      from public.hls_locations item where item.published
    ), '[]'::jsonb)
  );
$$;

create or replace function public.hls_get_media_usage(p_url text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case when public.hls_is_admin() then jsonb_build_object(
    'categories', (select count(*) from public.hls_product_categories where image = p_url),
    'products', (select count(*) from public.hls_products where p_url = any(images) or p_url = any(spec_images)),
    'locations', (select count(*) from public.hls_locations where image = p_url)
  ) else null end;
$$;

alter table public.hls_admins enable row level security;
alter table public.hls_product_categories enable row level security;
alter table public.hls_products enable row level security;
alter table public.hls_news enable row level security;
alter table public.hls_locations enable row level security;
alter table public.hls_inquiries enable row level security;
alter table public.hls_media enable row level security;

drop policy if exists "hls_admins_read_self" on public.hls_admins;
create policy "hls_admins_read_self" on public.hls_admins
for select to authenticated using (user_id = auth.uid());

drop policy if exists "hls_categories_admin_all" on public.hls_product_categories;
create policy "hls_categories_admin_all" on public.hls_product_categories
for all to authenticated using (public.hls_is_admin()) with check (public.hls_is_admin());
drop policy if exists "hls_products_admin_all" on public.hls_products;
create policy "hls_products_admin_all" on public.hls_products
for all to authenticated using (public.hls_is_admin()) with check (public.hls_is_admin());
drop policy if exists "hls_news_admin_all" on public.hls_news;
create policy "hls_news_admin_all" on public.hls_news
for all to authenticated using (public.hls_is_admin()) with check (public.hls_is_admin());
drop policy if exists "hls_locations_admin_all" on public.hls_locations;
create policy "hls_locations_admin_all" on public.hls_locations
for all to authenticated using (public.hls_is_admin()) with check (public.hls_is_admin());
drop policy if exists "hls_inquiries_admin_all" on public.hls_inquiries;
create policy "hls_inquiries_admin_all" on public.hls_inquiries
for all to authenticated using (public.hls_is_admin()) with check (public.hls_is_admin());
drop policy if exists "hls_media_admin_all" on public.hls_media;
create policy "hls_media_admin_all" on public.hls_media
for all to authenticated using (public.hls_is_admin()) with check (public.hls_is_admin());

-- The public website has no enquiry form. Keep historical enquiries accessible
-- only to authenticated hls_admins, and reject anonymous REST inserts.
drop policy if exists "hls_inquiries_public_insert" on public.hls_inquiries;

-- Create a PUBLIC Storage bucket named hls-site-assets in the Supabase dashboard.
-- Storage file operations must use the Storage API; these policies restrict
-- upload, replacement and deletion to users listed in public.hls_admins.
drop policy if exists "hls_storage_admin_insert" on storage.objects;
create policy "hls_storage_admin_insert" on storage.objects
for insert to authenticated
with check (bucket_id = 'hls-site-assets' and public.hls_is_admin());
drop policy if exists "hls_storage_admin_update" on storage.objects;
create policy "hls_storage_admin_update" on storage.objects
for update to authenticated
using (bucket_id = 'hls-site-assets' and public.hls_is_admin())
with check (bucket_id = 'hls-site-assets' and public.hls_is_admin());
drop policy if exists "hls_storage_admin_delete" on storage.objects;
create policy "hls_storage_admin_delete" on storage.objects
for delete to authenticated
using (bucket_id = 'hls-site-assets' and public.hls_is_admin());

revoke all on public.hls_admins, public.hls_product_categories, public.hls_products,
  public.hls_news, public.hls_locations, public.hls_inquiries, public.hls_media from anon, authenticated;
grant select on public.hls_admins to authenticated;
grant select, insert, update, delete on public.hls_product_categories, public.hls_products,
  public.hls_news, public.hls_locations to authenticated;
grant select, insert, update, delete on public.hls_inquiries to authenticated;
grant select, insert, update, delete on public.hls_media to authenticated;
revoke insert on public.hls_inquiries from anon;
grant usage, select on sequence public.hls_news_id_seq to authenticated;

revoke all on function public.hls_is_admin() from public;
grant execute on function public.hls_is_admin() to authenticated;
revoke all on function public.hls_get_site_content() from public;
grant execute on function public.hls_get_site_content() to anon, authenticated;
revoke all on function public.hls_get_media_usage(text) from public;
grant execute on function public.hls_get_media_usage(text) to authenticated;

-- After creating an admin in Authentication > Users, authorize that account:
-- insert into public.hls_admins (user_id)
-- select id from auth.users where email = 'your-admin@example.com'
-- on conflict (user_id) do nothing;
